Hw 17
MrNopi/internet-shop pull request #6
Opened 2020-01-14 09:52 UTC by MrNopi

2020-01-14 10:04 UTC, Sofasmile reviewed
знайшла e.printStackTrace(); в класі InjectorInitializer. і тут же потірбно кинути RuntimeException
не заставляй шукати далі по проекту)))
всі sout i printStackTrace - видалити з проекту

2020-01-14 10:04 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/controller/AddItemInBucketController.java
> +        logger.error("There is no such element");
тут доцільно логувати таке повідомлення?

2020-01-14 10:04 UTC, Sofasmile commented on src/main/webapp/WEB-INF/classes/log4j.properties
> +log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
додай пусту строку в кінці файлу

2020-01-14 13:31 UTC, boroda4436 requested changes

2020-01-14 13:31 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/implementation/BucketDaoImpl.java
> +        } catch (NoSuchElementException e) {
@MrNopi Чому ти вирішив відловлювати цей exception і логувати його? Ми говорили на лекції що ексепшини все одно залогуються. В цьому випадку - ти swallow the exception, і це мега погана практика, адже якщо в тебе фейлиться якась операція то щось йде не так. А ігноруючи exception - ти позбавляєш себе можливості виправити проблему через яку в тебе вилетів exception

2020-01-14 13:31 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/implementation/OrderDaoImpl.java
> +        } catch (NoSuchElementException e) {
@MrNopi прибери ці всі try-catch

2020-01-14 13:31 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/lib/Injector.java
> +            LOGGER.error("Class not found");
```suggestion
            throw new RuntimeException("Error while dependency injection occured ", e);
```

2020-01-14 15:55 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/dao/implementation/BucketDaoImpl.java
> +        LOGGER.error("Error occured when tried to update bucket");
в такому випадку навіть якщо все буде норм в тебе всеодно буде лог з ерором.
Просто повидаляй звідси логер, з усіх дао

2020-01-14 15:55 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/lib/Injector.java
> +        LOGGER.error("Class not found");
видалити

2020-01-14 15:55 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/services/implementation/BucketServiceImpl.java
> +        LOGGER.error("Error occured when tried to update bucket");
видалити

2020-01-14 15:55 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/services/implementation/ItemServiceImpl.java
> +    private static final Logger LOGGER = Logger.getLogger(ItemServiceImpl.class);
видалити

2020-01-14 15:55 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/services/implementation/UserServiceImpl.java
> +    private static final Logger LOGGER = Logger.getLogger(UserServiceImpl.class);
видалити

2020-01-15 08:20 UTC, Sofasmile reviewed
виправ ще один коментар + в класі InjectorInitializer є e.printStackTrace();
Заміни його на throw new Runtime...

2020-01-15 08:20 UTC, Sofasmile commented on src/main/java/mate/academy/internetshop/lib/Injector.java
> +        LOGGER.error("Class not found");
ще тут видали будь ласка

2020-01-15 10:03 UTC, Sofasmile approved these changes

2020-01-15 10:49 UTC, merged